<?xml version="1.0" encoding="UTF-8" ?> 
<!DOCTYPE automobil 
[
    <!ELEMENT automobil (model, tip, karakteristike)>
    <!ATTLIST automobil proizvodac CDATA "">
    <!ELEMENT model (#PCDATA)> 
    <!ELEMENT tip (#PCDATA)> 
    <!ELEMENT karakteristike (snaga, vrata)> 
    <!ELEMENT snaga (#PCDATA)> 
    <!ELEMENT vrata (#PCDATA)> 
]>

<!-- Root element: automobili --> 
<automobili> 
    <automobil proizvodac="Audi"> 
        <model>A4</model> 
        <tip>Limuzina</tip> 
        <karakteristike> 
            <!-- Snaga u ks -->
            <snaga>131</snaga> 
            <vrata>5</vrata> 
        </karakteristike> 
    </automobil> 

      <automobil proizvodac="Volkswagen"> 
        <model>Golf 6</model> 
        <tip>Karavan</tip> 
        <karakteristike> 
            <!-- Snaga u ks -->
            <snaga>105</snaga> 
            <vrata>5</vrata> 
        </karakteristike> 
    </automobil> 

      <automobil proizvodac="Fiat"> 
        <model>Punto</model> 
        <tip>Limuzina</tip> 
        <karakteristike> 
            <!-- Snaga u ks -->
            <snaga>70</snaga> 
            <vrata>3</vrata> 
        </karakteristike> 
    </automobil> 

</automobili> 